ARDUINO_DIR = /opt/arduino-1.8.13
ARDMK_DIR = $(HOME)/dev/Arduino-Makefile
AVR_TOOLS_DIR = /usr/include
BOARD_TAG = teensy41
TEENSY_USE_CLI=true
ARDUINO_LIBS = QuadEncoder ros_lib
include $(ARDMK_DIR)/Teensy.mk

